### ISSUE TITLE
bad generation for "public class Success<T> : IResponseDto where T : class"

### ISSUE THREAD

**Issue by CarlosOnline** [ffMathy/typescript-cs-poco#68]
Incorrect type is generated for the class  `public class Success<T> : IResponseDto where T : class`
Problem is the **where T : class**.

**Generated**
```
    export interface   {
        status: boolean;
        message: string;
        result: T;
...
```

**Source**
```
    public class Success<T> : IResponseDto where T : class
    {
        public bool Status { get; set; } = true;
        public string Message { get; set; }
        public T Result { get; set; }

        public Success(T data)
        {
            Result = data;
        }

        public override string ToString()
        {
            return Json.Serialize(this);
        }
    }
```

**Comment by ffMathy** [comment]
This library has now been deprecated in favor of https://github.com/ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator.

However, the new library has the same issue. I have therefore re-created the issue here: https://github.com/ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator/issues/1

It will be resolved within the next couple of days - and I hope you like the documentation and the syntax for the new library!
